css-brochure-form - Tré Mitchell
TreMitchell/c0824-code-solutions pull request #33
Opened 2024-09-05 19:55 UTC by TreMitchell

<img width="1433" alt="Screenshot 2024-09-05 at 12 54 07 PM" src="https://github.com/user-attachments/assets/145e44da-e8f1-44fb-abf3-72f05800c0fb">

2024-09-06 15:49 UTC, shawnkost requested changes
Solid first attempt! Some changes here

2024-09-06 15:49 UTC, shawnkost commented on css-brochure-form/index.html
> +            placeholder="sally@company.co" />
Missing an `id="email"` to match the `for` of the `label`

2024-09-06 15:49 UTC, shawnkost commented on css-brochure-form/index.html
> +          <input name="name" placeholder="Sally Smith" />
Missing an `id="name"` to match the `for` of the `label`

2024-09-06 15:49 UTC, shawnkost commented on css-brochure-form/index.html
> +          <input name="location" placeholder="City, Country" />
Missing an `id="location"` to match the `for` of the `label`

2024-09-06 15:49 UTC, shawnkost commented on css-brochure-form/styles.css
> +  justify-content: center;
If the `h2` doesn't have `display: flex`, this `justify-content` isn't doing anything

2024-09-16 23:10 UTC, TreMitchell commented
Added the IDs of name, email, and location while making the display of header 2 become flexed. The corrected code is in the other commit.

2024-09-17 21:04 UTC, shawnkost approved these changes
👍🏻

2024-09-18 16:20 UTC, merged