css-flexbox - Tré Mitchell
TreMitchell/c0824-code-solutions pull request #34
Opened 2024-09-05 23:24 UTC by TreMitchell

<img width="1103" alt="Screenshot 2024-09-05 at 3 58 51 PM" src="https://github.com/user-attachments/assets/ca3ce51c-1543-40f0-8958-6882245a43e7">
<img width="1436" alt="Screenshot 2024-09-05 at 3 59 01 PM" src="https://github.com/user-attachments/assets/7d33c5c8-72bf-47c8-a730-15bd156f22d5">
<img width="1440" alt="Screenshot 2024-09-05 at 3 59 07 PM" src="https://github.com/user-attachments/assets/7b6f4534-af46-428c-9f56-d1edb7574e73">
<img width="1440" alt="Screenshot 2024-09-05 at 3 59 17 PM" src="https://github.com/user-attachments/assets/14161d9b-30d3-4ca2-bceb-9cdec6315a9f">

2024-09-06 15:46 UTC, shawnkost requested changes
Couple small changes here!

2024-09-06 15:46 UTC, shawnkost commented on css-flexbox/align-items.html
> +        flex-basis: calc(100% / 3);
`flex-basis` is a child property which means it needs to be applied to flex children (an element who's direct parent has `display: flex`

2024-09-06 15:46 UTC, shawnkost commented on css-flexbox/justify-content.html
> +        flex-basis: 25%;
`flex-basis` is a child property which means it needs to be applied to flex children (an element who's direct parent has `display: flex`

2024-09-16 23:08 UTC, TreMitchell commented
Fixed the flex-basis issue of this assignment. The corrected code is on the other commit.

2024-09-17 21:01 UTC, shawnkost approved these changes
👍🏻

2024-09-18 16:21 UTC, merged